version: '3'

services:
  brainpower-nginx:
    restart: always
    build: build/nginx
    image: brainpower/nginx
    container_name: brainpower-nginx
    volumes:
      - "./volumes/nginx/log/:/var/log/nginx/"
      - "./build/nginx/brainpower.prod.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./build/certbot/www:/var/www/certbot/:ro"
      - "./build/certbot/conf/:/etc/nginx/ssl/:ro"
      - "..:/brainpower:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - brainpower
    depends_on:
      - brainpower-php-fpm

  brainpower-php-fpm:
    build: build/php-fpm
    image: brainpower/php-fpm
    container_name: brainpower-php-fpm
    volumes:
      - "..:/brainpower"
      - "./build/php-fpm/php.ini:/etc/php/8.1/fpm/php.ini:ro"
      - "./volumes/data:/opt/data"
    ports:
      - "127.0.0.1:9009:9000"
    networks:
      - brainpower
    depends_on:
      - brainpower-postgresql

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "./build/certbot/www/:/var/www/certbot/:rw"
      - "./build/certbot/conf/:/etc/letsencrypt/:rw"
    networks:
      - brainpower

  brainpower-postgresql:
    build: build/postgresql
    image: brainpower/db
    container_name: db
    environment:
      POSTGRES_PASSWORD: testpassW0000rdh
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "5432:5432"
    networks:
      - brainpower

networks:
  brainpower:
    external: true
