version: '3'

services:
  brainpower-nginx:
    build: build/nginx
    image: brainpower/nginx
    container_name: brainpower-nginx
    volumes:
     - "./volumes/nginx/log/:/var/log/nginx/"
     - "./build/nginx/brainpower.local.conf:/etc/nginx/conf.d/default.conf:ro"
     - "..:/brainpower:ro"
    ports:
     - "127.0.0.1:8000:80"
    networks:
     - brainpower
    depends_on:
     - brainpower-php-fpm

  brainpower-php-fpm:
    image: shrek100500/landing:test
    container_name: brainpower-php-fpm
    ports:
     - "127.0.0.1:9009:9000"
    networks:
     - brainpower
    depends_on:
     - brainpower-postgresql

  brainpower-postgresql:
    build: build/postgresql
    image: brainpower/db
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./volumes/pgdata:/var/lib/postgresql/data"
      - "./volumes/data:/opt/data"
    tmpfs:
      - /run
      - /tmp
    ports:
      - "5432:5432"
    networks:
      - brainpower

networks:
  brainpower:
    external: true
